remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: dotnet build -c Craftsmanship
description: 'Logging my Journey to Software Craftsmanship: [ projects, insights, media, sentiments ]'

navigation_links:
  Home: '/'
  My Style Guide - Practices: '/style_guide_practices.html'
  My Style Guide - Code: '/style_guide_code.html'
  Tech Advisory Board: '/tech_advisory_board.html'
  MeetUps / User Groups: '/meet_ups.html'
  Media Favourites: '/media_favourites.html'
  Artisanal Inspirations: '/artisanal_inspirational_sw.html'
  
